import { mdToHtml, PROVIDER_LABEL } from './api'

export const PageHead = ({ icon, tint, crumb, title, desc, actions }) => (
  <div className="pagehead">
    <div className="ptile" style={{ background: tint }}>{icon}</div>
    <div>
      <div className="crumb">{crumb}</div>
      <h1>{title}</h1>
      <div className="desc">{desc}</div>
    </div>
    {actions && <div className="actions">{actions}</div>}
  </div>
)

export const Md = ({ text }) => <div className="md" dangerouslySetInnerHTML={{ __html: mdToHtml(text) }} />

export const ModeTag = ({ mode }) => (
  <div className="provider-tag">
    {mode === 'offline'
      ? '⚙ Generated by the offline deterministic engine'
      : `✦ Generated by ${PROVIDER_LABEL[mode] || mode}`}
  </div>
)

export const HealthDot = ({ health }) => {
  const c = { healthy: 'var(--good)', degraded: 'var(--serious)', 'at-risk': 'var(--warn)', critical: 'var(--crit)' }[health] || 'var(--muted)'
  return <span className="health-dot" style={{ background: c }} />
}

export const SevBadge = ({ sev }) => <span className={`badge sev${sev.slice(3)}`}>{sev}</span>
